version: "3"

services:
    database:
        image: postgres
        container_name: database_preparame
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=admin@01
            - POSTGRES_DB=preparame
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: preparame
        restart: always
        ports:
            - 3334:3334
            - 9230:9230
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
